"""Expanding Database

Revision ID: cd5081c42b69
Revises: 
Create Date: 2023-07-13 00:48:41.406858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5081c42b69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mark_as_completed', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_due_date'))
        batch_op.drop_column('mark_as_completed')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
